### ISSUE TITLE
Support for Gnome 45

### ISSUE THREAD

**Issue by stouracp** [arahiko-ayami/gnome-shell-extension-regular-appmenu-icon#1]
Can you please provide migrated version for Gnome 45?

**Comment by arahiko-ayami** [comment]
I will update ASAP. However, I haven't upgraded to GNOME 45 yet, so I cannot test it right now

**Comment by stouracp** [comment]
Give me a link fo gnome 45 branch, and I will try it.

**Comment by stouracp** [comment]
Any news?

**Comment by Ticklezz** [comment]
Gnome 45 support coming?
